### PR TITLE
Initial Romanian translation

### PR DESCRIPTION
**Pull request by Cruel**
From DavidRO99 on GBATemp. Needs review.

### CODE REVIEW

**Comment by DAVIDRO999000999** [comment]
Found one problem 

> Completed is listed as Completand but should be Completat
`Completed: %s
Completat: %s
`

**Comment by Cruel** [comment]
Thanks. I added the changes. I also added "instalat" as missing translation for "installed".

Have you already tested it on your console to see if everything fits properly?

**Comment by DAVIDRO999000999** [comment]
Sorry that I couldnt respond, a lot of stuff was in my life. Anyways. Everything fits but these 3(Im on an XL model so idk for the smaller model) [http://imgur.com/a/DItyE](First) you could replace that with "Re-incarca Cache", [http://imgur.com/a/XiBpP](Second) you could replace that with "Nu selecta nimic", [http://imgur.com/a/SNw8b](Third) you could replace that with "Reseteaza"

**Comment by Cruel** [comment]
Thanks, I changed them. And the resolution for all 3DS models is the same, so screen size doesn't matter, they all look the same.

**Pull request merged**
