### PR TITLE
Update kr.lang(DavidKang)

### PR DESCRIPTION
**Pull request by mcloverkorea**
First draft.

### CODE REVIEW

**Comment by Cruel** [comment]
Looks great. There were a couple places where you used "freeshop" and one where you use "Freeshop". Just replace all instances with "freeShop", that's how it should be everywhere.

**Comment by mcloverkorea** [comment]
Dat. Auto cap. Dammit. Okay. I'll fix it.

**Comment by Cruel** [comment]
Also, put the newlines back in the first part, it's clearer when the translation lines are in pairs.

**Comment by mcloverkorea** [comment]
Oh I see. The numbering is different.

**Comment by mcloverkorea** [comment]
*fixed*

**Comment by Cruel** [comment]
I meant to use "freeShop" everywhere with capital S, that's technically how it should be.

**Comment by mcloverkorea** [comment]
Oooh... I will go fix it right away

**Comment by mcloverkorea** [comment]
Now, we'll have to test it.

**Comment by Cruel** [comment]
Thanks, it's merged now. 👍

**Pull request merged**
