### PR TITLE
Updated es_US.lang file with changes implemented from previous #153 and #154 pull requests.

### PR DESCRIPTION
**Pull request by ShadowOne333**
Reviewed the previous two Pull requests for the Spanish American translation and made a final revision fo the language renamed to en_US.lang

File attached as a .txt, simply rename it to en_US.lang:
[es_US.lang.txt](https://github.com/Cruel/freeShop/files/470424/es_US.lang.txt)

### CODE REVIEW

**Comment by Cruel** [comment]
I don't think this Pull Request is made properly. You're merging a translation branch that has changes to es.lang but it seems you're just wanting to submit es_US.lang, right ?

**Comment by ShadowOne333** [comment]
Yeah, sorry, I don't know how to make a proper pull request in Github :/
So I just added the file as an attachment.

The es_US.lang file contains changes that have been made in the previous requests #153 and #154.
But since I'm not sure if you want to make two separate spanish lang or just one, I renamed it to es_US.lang instead of es.lang, but it is indeed a change of es.lang.

You can merge as  es.lang.if you want to

**Comment by Cruel** [comment]
I have already split into es_US.lang and es_ES.lang

So if you could, just go here:
https://github.com/Cruel/freeShop/blob/master/res/romfs/lang/es_US.lang

Then you can click on the edit button and copy your revisions in to submit it as a PR. Look over it and make sure it's suitable for American Spanish (both North/South American).

Also, were #153 and #154 Spanish or American? Just need to now if they should be put in es_ES.lang or not.

**Comment by ShadowOne333** [comment]
Thank you!
I already sent the submission for the es_US.lang :)

Also, both 153 and 154 seem to be quite neutral.
I didn't spot any word that's present in only one spanish or the other. Although I think 154 might be made by a European spanish user, so you could use that one as the base for es_EU.lang

I want to believe they are spanish American since they used "cola de" instead of "fila de", and European spanish uses "cola" as a bad word. So yeah, I think they both are based on American spanish.

**Pull request closed without merging**
