### PR TITLE
Update pt.lang

### PR DESCRIPTION
**Pull request by poutros**
Cache is a feminin word.
<br />Screenshots has a plausible portuguese translation. No need for english.
<br />Save data is called dados de gravação by nintendo itself so I assume people will recognise it better.
<br />Although "de" can be used, we are talking about a specific filter and not a random filter. As such, it is more correct to say "do filtro" and not "de filtro".
<br />I don't think I really need to explain the "Tudo"->"Selecionar Tudo" and such. It's just a more precise translation.
<br />"Detecção" is obsolete with new portuguese rules from a few years ago (I'm not exactly sure about brazil's stance on this but I assume it never had the "c" there)
<br />What was that "de" even doing there?
<br />
<br />Most other things that may seem incorrect, I left them because it's probably just a difference of pt-br and pt-pt other than an actual mistake.

### CODE REVIEW

**Comment by Cruel** [comment]
Thanks.

The current Portuguese will probably be pt-br (I'll perhaps rename it pr-br.lang). So "ecrã" should probably be "tela" since that's the most common I've heard. Also, I removed "Selecionar" because it doesn't fit on the button, and it's already clear what the button does without it. Though perhaps "todos" would be better than "tudo"? Not sure it matters...

I'll probably add European Portuguese and Spanish later.

**Comment by poutros** [comment]
Yeah, I thought that would be the case for selecionar.

**Comment by poutros** [comment]
I deleted "Selecionar" and changed "Tudo" to "Todos". I also renamed "ecrã" to "tela"

**Comment by Cruel** [comment]
Hey, sorry for ignoring your PR, I just was waiting until the BR and PT translations were separated. They are now separated so this PR needs revision to change both files: [pt_BR](https://github.com/Cruel/freeShop/blob/master/res/romfs/lang/pt_BR.lang) [pt_PT](https://github.com/Cruel/freeShop/blob/master/res/romfs/lang/pt_PT.lang)

Also, unless a reason can be given otherwise, masculine cache seems more correct based on how I've seen it used/defined:
https://pt.wikipedia.org/wiki/Cache
http://michaelis.uol.com.br/busca?r=0&f=0&t=0&palavra=cache
https://pt.wiktionary.org/wiki/cache

But I have indeed seen it defined as feminine too: http://www.infopedia.pt/dicionarios/lingua-portuguesa/cache

Not sure if it's just an inconsistency based on being of English origin or a PT/BR difference. If you know more or have better examples of feminine usage, let me know.

Other changes:
- Detecção seems to be used in BR and Deteção in PT.
- Ecrã can be brought back for PT now that the file exists.

With those changes, I will merge. You'll probably have merge conflicts now, but if you need to make a new PR or have a merge commit here, doesn't matter. Thanks!

**Comment by poutros** [comment]
I'll probably have masculine cache for pt br and feminin cache for pt pt since that's what it seems to be.

**Comment by poutros** [comment]
I'll rebase and open a new pull request because github is playing hard to get.

**Pull request closed without merging**
